export const GET_WINES = "GET_WINES";

export const GET_NAME_WINE = "GET_NAME_WINE";

export const CREATE_WINE = "CREATE_WINE";

export const GET_REVIEW_BY_ID = "GET_REVIEW_BY_ID";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const SEND_TO_CART = "SEND_TO_CART";

export const SUM_CART_VALUES = "SUM_CART_VALUES";

export const UPDATE_USER = "UPDATE_USER";

export const GET_USER_REVIEWS = "GET_USER_REVIEWS";

export const DELETE_FAVORITES = "DELETE_FAVORITES";

export const GET_FAVORITES = "GET_FAVORITES";

export const USER_BY_EMAIL = "USER_BY_EMAIL";
export const GET_ORDERS = "GET_ORDERS";
export const PUT_PRODUCT_STATE = "PUT_PRODUCT_STATE";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const CREATE_CATEGORY = "CREATE_CATEGOTY";
export const GET_USERS = "GET_USERS";
